### ISSUE TITLE
使用SauceNAO在群聊搜图时出现标题文本及url重复输出

### ISSUE THREAD

**Issue by YuuzukiRin** [lgc-NB2Dev/YetAnotherPicSearch#137]
### YetAnotherPicSearch 、 PicImageSearch 、 go-cqhttp 、 nonebot 、 Python 版本及操作系统

YetAnotherPicSearch 2.0.0
nonebot 2.3.2
Python 3.10.9
LLOneBot v3.27.3
Windows 10 22H2

### 列出安装的 Python 包

nb-cli

### 如何复现

群聊中使用'搜图'命令, 出现以下运行结果, 标题, url会在缩略图上重复输出:
![0ec0024b5fc8c5d3e54f6d323425dc97](https://github.com/user-attachments/assets/04a64feb-fea3-49a4-a29d-0bfa446200b2)
在此基础上, 在有图片缓存的状态下, 搜索同一张图, 也是如此:
![712055f40768aa0c54ef669e16952cd2](https://github.com/user-attachments/assets/8897ccbc-ee4c-4849-8199-645fa0015b7f)
如果搜索一张图重复次数增加, 则会出现重复引用回复:
![491a9c576ec0e985fec0dc2e0f470604](https://github.com/user-attachments/assets/a3dfaed2-1ab1-4eb7-a9f8-f19bfe56ea8f)

### 期望行为

在私信中则不会出现这样的问题:
![cb12ad544fdefd825ef48ab2e34d3511](https://github.com/user-attachments/assets/f96dda0a-8bfc-4725-a940-de4fbe31ca2b)
如果设置HIDE_IMG= True , 则群组中也不会出现重复:
![589801e71898943a133ff3a80f8e935d](https://github.com/user-attachments/assets/1c2df147-cdd3-4c91-b8ef-ae45cf79db5c)

### 实际行为

群聊日志：
<img width="724" alt="image" src="https://github.com/user-attachments/assets/36ec52f0-87da-42ef-a2fe-4113753f5279">
<img width="719" alt="image" src="https://github.com/user-attachments/assets/5eb2dd5f-c78e-47a9-ae1b-15939efb1bb1">
私信日志：
<img width="725" alt="image" src="https://github.com/user-attachments/assets/da4ac35b-5c91-4496-b5f6-234446a8a1eb">
另: 
不论是否配置excookie, 使用'搜图 --ex'搜图均显示EHentai暂时无法使用:
![068154dca90e58c34a07d0841adbd106](https://github.com/user-attachments/assets/1c7f0c0b-e126-4428-9d72-50703421dc01)
已知并没有配置PROXY, win10本地运行clash, 能够连接eh, 在关闭clash代理后便无法连接报错显示搜索失败, ex在浏览器能够正常登录; .env.prod配置格式如下, 已确认cookie是正确的
EXHENTAI_COOKIES="ipb_member_id=XXX; ipb_pass_hash=XXX; yay=XXX; igneous=XXX"
想知道这是代理配置的问题, 还是输入cookie的格式有误(或其他可能原因)

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/YetAnotherPicSearch/releases/tag/v2.0.1
